### ISSUE TITLE
resursa non-https pe pagina https

### ISSUE THREAD

**Issue by rredpoppy** [gov-ithub/volunt-app#12]
pe pagina de profil
![screenshot from 2016-11-14 12-19-43](https://cloud.githubusercontent.com/assets/902317/20261501/b938e796-aa66-11e6-8c82-d56be87e73c2.png)

**Comment by rredpoppy** [comment]
pare ok acum, nu mai este warning

**Comment by rusanu** [comment]
Fixed with https://github.com/gov-ithub/volunt-app/commit/7a3ec9c87b33242b7e8e989a958f8cd4c47480f2
