### ISSUE TITLE
Projects/Openings

### ISSUE THREAD

**Issue by oserban** [gov-ithub/volunt-app#15]
Pagina de proiecte de pe gotithub ar trebui mutata pe volunt-app si sa contina in plus:
- persoana de contact
- status proiect
- link github
- link issue tracker: github, jira, etc
- descriere tehnologii folosite
- status recrutare voluntari -> openings

Istoricul de pe govithub e foarte interesant, dar ar putea fi mutat intr-o sectiune separata cu date extinse despre proiect.

Openings devine doar o agregare a tuturor posturilor deschise in fiecare proiect a.i. coordonatorul proiectului nu mai trebuie sa posteze openings inafara proiectului sau.

**Comment by rusanu** [comment]
In principiu acuma cam toate acestea sunt rezolvate. Proiectele sunt vizibile, la fel si opennings. La proiecte sunt link-uri explicit pt. JIRA, Confluence, GitHub etc. Mai departe este o problema ca coordinatori de proiecte sa-si updateze proiectele in volunt-app
