### ISSUE TITLE
Unable to Edit Profile

### ISSUE THREAD

**Issue by mimarcel** [gov-ithub/volunt-app#16]
### Preconditions
- Logged-in https://voluntari.ithub.gov.ro

### Steps to Replicate
- Click Edit.
- Click Save.

### Expected result
- Get redirected back
- Profile is saved
- see Success Message that profile was saved

### Actual result
- Get redirected back
- Profile is not saved
- see Error Message
<img width="631" alt="we_re_sorry__but_something_went_wrong__500_" src="https://cloud.githubusercontent.com/assets/2362026/20455240/ee6c3038-ae5f-11e6-943f-75d656fc1eea.png">

### Note
This used to work a few days ago.

**Comment by mess110** [comment]
I tried the steps on my account but I couldn't reproduce.

I guess some of the data entered is invalid or something of the sort and is not correctly handled. Could you please give some more details about the input data you are using?

note: exclude personal information pls

**Comment by mimarcel** [comment]
@mess110 I sent you a message on Slack.

**Comment by rusanu** [comment]
````
    @profile.hidden_tags << 'SELF UPDATED' if !is_user_level_fellow?\$
         and !@profile.hidden_tags.include? 'SELF UPDATED'$
```
Daca `hidden_tags` e nil, kaboom.

**Comment by rusanu** [comment]
Problema apare in mail multe locuri unde manipulam PG array fields, si ar trebuii fixata in `app/models/concern/tags_concer.rb` . Working on it.

**Comment by rusanu** [comment]
ps. eu am access la production.log si vad unde este problema

**Comment by rusanu** [comment]
@mimarcel poti sa-mi spui daca merge acum? Am facut un fix https://github.com/gov-ithub/volunt-app/commit/a9e2626ec6045c96398553a4023633c263f474e1

**Comment by mimarcel** [comment]
S-a rezolvat.
