### ISSUE TITLE
Legatura intre acest proiect si site-ul unde ruleaza

### ISSUE THREAD

**Issue by ciprianpavel** [gov-ithub/volunt-app#22]
Pe site-ul http://voluntari.ithub.gov.ro/ este mentionat sursa proiectului, dar plecand de la sursa proiectului nu ajungi intr-un mod facil catre http://voluntari.ithub.gov.ro/.
Propun ca link-ul http://voluntari.ithub.gov.ro/sa fie mentionat in README-ul proiectului.

**Comment by rusanu** [comment]
@ciprianpavel  Poti te rog sa submiti un pull request cu fix in README.md?
