### ISSUE TITLE
Pagina de profil + lista volunteer/applicant - afisare data inregistrarii (Member since)

### ISSUE THREAD

**Issue by alexchiraples** [gov-ithub/volunt-app#23]
Pe pagina de profil a voluntarului/aplicantului ar fi util sa vedem data inregistrarii.
Pregatim astfel o filtrare: ce persoane au aplicat in ultimele [X] saptamani si nu sunt asociate la un proiect.

**Comment by mess110** [comment]
Să adăugăm asta?

![image](https://cloud.githubusercontent.com/assets/226170/20608705/d87b0796-b28c-11e6-8afc-4dd7ff8e78ac.png)

**Comment by alexchiraples** [comment]
Asta e, da :)
