### ISSUE TITLE
Daca se editeaza email-ul userii au probleme sa-si regaseasca profilul

### ISSUE THREAD

**Issue by rusanu** [gov-ithub/volunt-app#30]
Nu ar trebuii permisa editarea email-ului principal.

**Comment by rusanu** [comment]
Profile email are mai multe probleme. In primul rind nu avem uniquness constaint pe intreg spatiul de email (email in contacts pot fi duplicate intre profile). Si cautarea dupa email (`Profile.for_email`) cauta dupa tag-uri hard codded (`email`, `email1`, `email2` si `email3`). Trebuie separata emails in table proprie, `belongs_to :profile` si `Profile has_many :emails`.

Apoi putem adresa si problema de self-update a adresei de email vis-a-vis login. Planul meu era ca un user sa nu-si poata modifica email-ul *cu care a facut login*. Pentru schimbare de email flow-ul ar fi:
 
1. Adauga noul email in profilul personal
2. Face signout
3. Face sign-in cu noul email (#31 fixeaza problemele cu sign-in si password reste cu email secundar)
4. Modifica emailul principal (mai exact, promoveaza noua adresa de email ca 'adresa principala')

**Comment by alexchiraples** [comment]
Issue migrated to civictechro/volunt-app#27
