### ISSUE TITLE
Forgot password page is not clear about the need to sign-up before request reset 

### ISSUE THREAD

**Issue by danichim** [gov-ithub/volunt-app#44]
Daca un utilizator neinregistrat da forgot ii apare text ca i-a fost trimis un mail, desi el nici nu avea cont.
Cred ca ar fi util o verificare daca exista acel email in baza de date.

**Comment by rusanu** [comment]
Este o procedura standard de securitate ca mesajul sa fie identic si in cazul in care user-ul exista si in cazul in care nu exista. Altfel exista 'information disclosure' pentru un user neauthentificat, princ care un atacator poate vedea daca un email este sau nu este in sistem cerind sa se resetetze parola la o adresa de email si observind daca mesajul este unul sau celalt.
Dar Dan are dreptate ca pagina de password reset nu este destul de clara ca user-ul trebuie sa faca sign-up daca nu a facut deja.
O alta varianta este sa tratam cererea de resetare a parolei automat ca o cerere de sign-up, daca nu exista userul respectiv.

**Comment by rusanu** [comment]
Fixed with #46
