### ISSUE TITLE
Sortare dropdowns in ordine alfabetica

### ISSUE THREAD

**Issue by carol-braileanu** [gov-ithub/volunt-app#9]
Informatiile afisate in dropdowns (bursieri, voluntari, etc) ar trebui sortate in ordine alfabetica, pentru a fi mai usor de gasit. 
O alta idee pentru o functionalitate si mai buna ar fi folosirea unei componente gen `select2`: https://select2.github.io/, care are functionalitate de search integrata si este foarte usor de implementat.

**Comment by rusanu** [comment]
Acuma numele sunt sortate alphabetic si mai usor de gasit. Nu avem cod JS in front-end ca sa facem un select mai smart, gen auto-complete.
